# Generated by Django 6.0.2 on 2026-03-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('TECHNICAL', 'Technical'), ('HARDWARE', 'Hardware'), ('BILLING', 'Billing'), ('OTHER', 'Other')], default='TECHNICAL', max_length=20),
        ),
    ]
