# Generated by Django 6.0.2 on 2026-03-05 16:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='vendor',
            new_name='assigned_vendor',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='buyer',
            new_name='buyer_user',
        ),
        migrations.AddField(
            model_name='ticket',
            name='buyer_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='buyer_name',
            field=models.CharField(default='Pending User', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='buyer_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='company',
            field=models.CharField(default='YBL', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='subcategory',
            field=models.CharField(choices=[('LDAP', 'LDAP / Authentication'), ('APP', 'Application Interface'), ('NETWORK', 'Network Connectivity'), ('CTS', 'CTS Service'), ('DATABASE', 'Database Management'), ('INVOICE', 'Billing/Invoice Issue')], default='APP', max_length=50),
        ),
    ]
