# Generated by Django 6.0.2 on 2026-03-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticket_buyer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_vendor',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='ticket',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('TECHNICAL', 'Technical'), ('HARDWARE', 'Hardware'), ('BILLING', 'Billing')], default='TECHNICAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low (10 Days)'), ('MEDIUM', 'Medium (5 Days)'), ('HIGH', 'High (2 Days)')], default='LOW', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
    ]
